### ISSUE TITLE
Security To-Do List

### ISSUE THREAD

**Issue by JadedChara** [CharaHarimata/Terminus-game-dev#7]
'Bout time I get around to this one! Before I make any other significant changes a lot of these need to be focused on.

* [X] Movement handlers shifted to server-side.
* [ ] Keyboard input transmitted instead of movement mappings.
* [ ] Local password storage and obfuscation (Maybe MD5?)
* [X] Account Checks
* [ ] Captchas and bot-proofing
* [ ] IP banning (Might be tricky because of the system primarily using websockets)
* [ ] Clean up `html` file for better reference
* [ ] Script detection
* [ ] Injection?
* [ ] JSON storage
* [ ] CSS/HTML modification detection? Somehow?
* [ ] Browser recognition

**Comment by JadedChara** [comment]
@Minion3665 I've found a good solution in the form of `aes-js`, so I can finally store account details! Whoo!
